FROM python:3.12.4-bullseye

RUN apt update -y && apt upgrade -y
RUN pip install pipenv 

WORKDIR /model

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENV PYTHONPATH=/model/src

ENTRYPOINT ["./entrypoint.sh"]
