FROM python:3.12.4-bullseye

RUN apt update -y && apt upgrade -y
RUN pip install pipenv 

WORKDIR /model

COPY Pipfile.lock .
RUN pipenv sync 

RUN echo "PS1='\[\e[32m\]\u@ana-model:\w\[\e[0m\]$ '" >> /root/.bashrc

ENV PYTHONPATH=/model/src

CMD ["pipenv", "shell"]
