# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x04\x63ore\"\x16\n\x06Prompt\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x10PromptCompletion\x12\x0c\n\x04text\x18\x01 \x01(\t2A\n\x05Model\x12\x38\n\x0e\x63ompletePrompt\x12\x0c.core.Prompt\x1a\x16.core.PromptCompletion\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROMPT._serialized_start=20
  _PROMPT._serialized_end=42
  _PROMPTCOMPLETION._serialized_start=44
  _PROMPTCOMPLETION._serialized_end=76
  _MODEL._serialized_start=78
  _MODEL._serialized_end=143
# @@protoc_insertion_point(module_scope)
