FROM python:3.10.11

WORKDIR /apps

COPY . .

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "-m", "core"]

# from senti
FROM python:3.9-bookworm

RUN apt update 

WORKDIR /senti

RUN pip install pipenv

ENV PYTHONPATH=/senti/src
