FROM python:3.9.16-bullseye

WORKDIR /apps

RUN git clone https://github.com/austinagii/gibber.git

WORKDIR /apps/gibber/gibber-api

RUN pip install pipenv && pipenv sync

ENTRYPOINT pipenv run uvicorn --host 0.0.0.0 src.gibber:app 