#!/bin/bash

# if [ -n "`docker images | awk '$1 == "gibber/build-agent" {print; exit}'`" ]; then echo "Build agent image exists"; else echo "Could not find build agent image. Try running 'gibber init' first"; fi

# if [ -n "`docker images | awk '$1 == "gibber/build-agent" {print; exit}'`" ]; then echo "Build agent image exists"; else echo "Could not find build agent image. Try running 'gibber init' first"; fi

# Let's start with the simple top level commands 
# These are:
#   init
#   build
#   start

SCRIPT_DIR=$(dirname $(realpath $0))

case $1 in
    init) 
        echo "Initializing gibber..."
        echo
        IMAGE_ID=$(docker image build -q -t gibber/build-agent $SCRIPT_DIR/../build)
        echo "Build agent image successfully created with id: $IMAGE_ID"
        ;;
    build)
        echo "You are attempting to build gibber"
        ;;
    start)
        echo "You are attempting to start gibber"
        ;;
    *)
        echo "Unrecognized command '$1'"
        ;;
esac