#!/bin/bash

# Get the current directory
export SCRIPT_DIR=$(dirname $(realpath $0))
# Get the root directory of the project
export ROOT_DIR=$(dirname $SCRIPT_DIR)
# Get the root directory of the Gibber API
export API_ROOT_DIR=$ROOT_DIR/gibber-api
# Get the root directory of the Gibber UI
export UI_ROOT_DIR=$ROOT_DIR/gibber-ui
